### ISSUE TITLE
Template name created as a directory inside the brick name while creating new bricks

### ISSUE THREAD

**Issue by hrisheekeshr** [lumoz-ai/brick-python-sdk#15]
In version, bricksdk==0.1.5, when a new brick is created using

`brick create -n brick_name -f template_name`, 

instead of the files displaying inside the brick_name folder (brick_name/{contents}, it creates another folder brick_name/template_name/{contents}/. 

If you cd into the template_name directory, you can run the `brick proto -d` command and `brick proto -c` command as a temporary workaround.

**Comment by ramachandranrishi** [comment]
The easier way to handle this solution is to restructure the zip files in the [`template-store`](https://github.com/lumoz-ai/lumoz-brick-template-store) repo.

**Comment by ramachandranrishi** [comment]
@hrisheekeshr I have changed the folder structures of the template zip files in the template-store repo. I am closing this issue here.
